Algoritmo "Primeiros Comandos"
// Disciplina   : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   : AOrimeiros comandos aqui
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/08/2024
Var
   // Seção de Declarações das variáveis
   msg: caractere

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   msg <- "Olá Mundo!"
   Escreval("Mensagem: ", msg)

Fimalgoritmo